#:schema /home/kjanat/projects/zed-editor/crates/extension_api/schemas/language-config.schema.json

name                          = "JSON"
grammar                       = "json"
path_suffixes                 = ["turbo.json", "turbo.jsonc", "package.json"]
line_comments                 = ["// "]
tab_size                      = 2
scope_opt_in_language_servers = ["json-language-server"]
prettier_parser_name          = "jsonc"
code_fence_block_name         = "jsonc"
brackets                      = [
  { start = "{", end = "}", close = true, surround = true, newline = true, not_in = ["string", "comment"] },
  { start = "[", end = "]", close = true, surround = true, newline = true, not_in = ["string", "comment"] }
]

[block_comment]
start    = "/*"
end      = "*/"
prefix   = "*"
tab_size = 1

[documentation_comment]
start    = "/**"
prefix   = " * "
end      = "*/"
tab_size = 2

[wrap_characters]
start_prefix = "\""
start_suffix = ""
end_prefix   = ""
end_suffix   = "\""
